### ISSUE TITLE
suggested feature enhancement to future version of Bagger

### ISSUE THREAD

**Issue by houzanme1** [LibraryOfCongress/bagger#17]
This is just a suggested feature enhancement:
When a created bag is tempered with such as deleting a few files from the "data" folder, Bagger correctly identifies the files that are missing and lists them upon bag validation. That's very helpful in identifying exactly where the issues are.

Now the suggested feature: Suppose the Hash values (MD5 or SHAx) are tempered with, either in the manifest-*.txt and/or the tagmanifest-*.txt files, it would be helpful to know exactly which files are affected that are in the "data" folder. 

The idea is to not reject a whole bag when one or two items are tempered with or became corrupt.

**Comment by johnscancella** [comment]
@houzanme1 Please provide an example of the expected behavior as it is not exactly clear what you are suggesting. 
For example:
given a bag that has one file corrupt in its data directory when bagger is used to verify it lists the one file that is corrupt. 
Or: 
step 1 - create a bag
step 2 - modify manifest-MD5.txt changing one of the hashes and save
step 3 - open bag in bagger
step 4 - verify bag
expected output - bagger displays only files that are corrupt.

**Comment by johnscancella** [comment]
Bagger 2.4 already does this, see screenshot
![screen shot 2016-02-05 at 2 47 43 pm](https://cloud.githubusercontent.com/assets/8711605/12857320/8088e316-cc17-11e5-8c2d-c7373fde23bf.png)

**Comment by houzanme1** [comment]
My apologies, John. That is the same outcome I got this time. So, you are right, it does correctly list the files tempered with. Perhaps I looked at a different result. 
Tibaut

**Comment by johnscancella** [comment]
@houzanme1  no problem, it happens!
