### ISSUE TITLE
Version 2.7.7 fails to start

### ISSUE THREAD

**Issue by ShakeyDave** [LibraryOfCongress/bagger#49]
I've just downloaded 2.7.7 from the releases page and, when running the bagger shell script, I received the message: 

`Error: Could not find or load main class gov.loc.repository.bagger.BaggerApplication`

2.7.6 seems to load up and run absolutely fine.

This all happened on Mac OSX El Capitan.

I guess it's just a little error in how the release might have been packaged up, or something? 

All the best and thanks.

**Comment by johnscancella** [comment]
Thanks for reporting this! I must have built it with java 9 by mistake which left out the classes needed due to the new way it packages jars. I created a new 2.7.7 and verified that it works on my mac OS laptop. It has been re-uploaded to the releases page with updated md5 and sha256 checksums for verification.
